### ISSUE TITLE
Docker Container error

### ISSUE THREAD

**Issue by Nalum** [hnlq715/nginx-vts-exporter#15]
I'm starting Nginx up within kubernetes and using the container `sophos/nginx-vts-exporter:latest`, when kubernetes starts the pod and creates the exporter container it throws the following error:

```
tar: /bin/nginx-vts-exporter: not found in archive
```

Using `sophos/nginx-vts-exporter:v0.4` has resulted in:

```
Connecting to github.com (192.30.253.112:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

**Comment by hnlq715** [comment]
Got it! I would fix it ASAP, thanks~

**Comment by hnlq715** [comment]
@Nalum  Please try again

**Comment by Nalum** [comment]
@hnlq715 `latest` is working now. :+1:

I assume you wanted me to test before you updated `v0.4` or added a new version?

**Comment by hnlq715** [comment]
I have added a new version v0.5 :-)
