### ISSUE TITLE
how to start nginx-vts-exporter in gitlab9.4...

### ISSUE THREAD

**Issue by denglitong** [hnlq715/nginx-vts-exporter#27]
Here I'm so sorry..but I really can not solve it. my problem is, how to install and start nginx-vts-exporter correctly.
i install gitlab with rpm and it's version is 9.4.2, i do as the guide md but not get expected result, i add the config in  : /var/opt/gitlab/nginx/conf/nginx.conf

server {
      listen      9914;
      server_name 10.21.20.124;
              
      location /status {
          vhost_traffic_status_display;
          vhost_traffic_status_display_format html;
      }   
  }

but in this way i can not restart the nginx with `gitlab-ctl restart nginx` which will raise a timeout error.
due to not configing nginx correct so when i run nginx-vts-exporter:
`nohup /bin/nginx-vts-exporter -nginx.scrape_uri=http://localhost:9914/status/format/json`
it will tell get timeout error.

i am not sure it's a right place to ask this ques, but i really don't know when to find help. you know the doc is rare for me, thanks really much! waitting for your responce.
other: install nginx-vts-exporter with command `go get github.com/hnlq715/nginx-vts-exporter ` and start nginx-vts-exporter  in the dir GOPATH/bin/

**Comment by hnlq715** [comment]
change server_name to localhost and retry 😄

**Comment by denglitong** [comment]
After changing ip to localhost, here is what i get from gitlab-ctl: 
[root@SZX1000347429 conf]# gitlab-ctl restart nginx
timeout: down: nginx: 1s, normally up, want up

I see that the installation for the nginx-modult-vts has 

1.Clone the git repository.
  shell> git clone git://github.com/vozlt/nginx-module-vts.git
2.Add the module to the build configuration by adding --add-module=/path/to/nginx-module-vts
3.Build the nginx binary.
4.Install the nginx binary.

So I wonder if it's that I don't add nginx-module-vts correctly to nginx in gitlab9.4 ? How to do it? Does it need to build  and install nginx binary? Thanks so much!

**Comment by hnlq715** [comment]
Of course you should build a new nginx binary.
try `nginx -V` and you can see if this module is installed.

**Comment by denglitong** [comment]
thanks for your answer, i will try it :)
