### ISSUE TITLE
[ Question ]How to define the job in prometheus.yml?

### ISSUE THREAD

**Issue by regardfs** [hnlq715/nginx-vts-exporter#28]
Hi, I find there few doc about how to implement this in prometheus, below is my configuration 
**prometheus.yml**

>   \- job_name: 'nginx-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ["http://172.17.15.101/status/format/json"]
    relabel_configs:
      - source_labels: [\_\_address\_\_]
        regex: (^http://.*)
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: host
      - source_labels: []
        regex: .*
        target_label: \_\_address\_\_
        replacement: 172.17.15.101:9913

**docker-compose.yml**

>   nginx-exporter:
    image: sophos/nginx-vts-exporter
    ports:
      \- 9913:9913
    environment:
      NGINX_HOST: "http://172.17.15.101/status/format/json"

* Question 1.  how to set monitor endpoint(s)?
* Question 2. how to implements this in prometheus.yml?

Thanks a ton....T T, wait for u help.

**Comment by hnlq715** [comment]
targets in `prometheus.yml` should be the address of `nginx-vts-exportor`.
For example
```
 - targets: ["http://172.17.15.101:9913"]
```
