### ISSUE TITLE
[Optimize] Health check scraping website page like "/health" or "/metrics" will contaminate the website visit statistics  

### ISSUE THREAD

**Issue by regardfs** [hnlq715/nginx-vts-exporter#30]
Hi:
    As I said in issue title, exporter scrape page like /health or /metrics/format/json will contaminate website visit statistics, Those visits have no relationship with real service.
   I deem that this could be optimize in ngx-vts-module, but could we do sth in this exporter?

**Comment by hnlq715** [comment]
This could be solved by proper nginx config. 😃
And as far as I'm concerned, `nginx-vts-module` should have directory to do this stuff.

**Comment by regardfs** [comment]
@hnlq715
I had try to find this directory in ngx-vts-module, but not yet >_<

**Comment by regardfs** [comment]
@hnlq715
Hi , I have found that the directories as below, thanks a ton
>  vhost_traffic_status_bypass_limit
vhost_traffic_status_bypass_stats
