### ISSUE TITLE
Running nginx-vts-exporter and got error:

### ISSUE THREAD

**Issue by smallfish01** [hnlq715/nginx-vts-exporter#32]
# ./nginx-vts-exporter &
[1] 14394
[root@office-monitoring nginx-vts-exporter-0.6.linux-amd64]# 2017/09/05 08:58:48 Starting nginx_vts_exporter (version=0.6, branch=HEAD, revision=e48bd6899d8864b11b9f71f852b049ec3ad2ae26)
2017/09/05 08:58:48 Build context (go=go1.8.3, user=root@3b0fc1d0acb6, date=20170808-07:09:08)
2017/09/05 08:58:48 Starting Server at : :9913
2017/09/05 08:58:48 Metrics endpoint: /metrics
2017/09/05 08:58:48 Metrics namespace: nginx
2017/09/05 08:58:48 Scraping information from : http://localhost/status
2017/09/05 08:58:51 json.Unmarshal failed invalid character '<' looking for beginning of value
2017/09/05 08:59:06 json.Unmarshal failed invalid character '<' looking for beginning of value
2017/09/05 08:59:21 json.Unmarshal failed invalid character '<' looking for beginning of value
2017/09/05 08:59:36 json.Unmarshal failed invalid character '<' looking for beginning of value
2017/09/05 08:59:51 json.Unmarshal failed invalid character '<' looking for beginning of value
2017/09/05 09:00:06 json.Unmarshal failed invalid character '<' looking for beginning of value
2017/09/05 09:00:21 json.Unmarshal failed invalid character '<' looking for beginning of value
2017/09/05 09:00:36 json.Unmarshal failed invalid character '<' looking for beginning of value

Do you konw how to resolving the issue as above?

Thank you!

**Comment by hnlq715** [comment]
You should make sure `http://localhost/status` is the url where vts-module exposes its metrics.

I think this is the point you should take into account.

**Comment by smallfish01** [comment]
Yes, I can access http://localhost/status from my browser.

**Comment by hnlq715** [comment]
And this url should return json format metrics.

**Comment by smallfish01** [comment]
Hi hnlq715,
Thanks for your help, I tried change nginx.conf and change the code "vhost_traffic_status_display_format html;" to "vhost_traffic_status_display_format json;" and now it's ok:
 ./nginx-vts-exporter &
[1] 4941
# 2017/09/08 08:31:56 Starting nginx_vts_exporter (version=0.6, branch=HEAD, revision=e48bd6899d8864b11b9f71f852b049ec3ad2ae26)
2017/09/08 08:31:56 Build context (go=go1.8.3, user=root@3b0fc1d0acb6, date=20170808-07:09:08)
2017/09/08 08:31:56 Starting Server at : :9913
2017/09/08 08:31:56 Metrics endpoint: /metrics
2017/09/08 08:31:56 Metrics namespace: nginx
2017/09/08 08:31:56 Scraping information from : http://localhost/status

But I have another questions, "nginx-vts-exporter" process will terminated automatically about in a day, do you konw how can I setup log and to find the root cause?

**Comment by hnlq715** [comment]
Glad to here this 😃 
The log of `nginx-vts-exporter` would direcetly print into stdout, and you can use `nohup ./nginx-vts-exporter &` to capture log into `nohuo.out` file.

**Comment by smallfish01** [comment]
I created log file for nginx-vts-exporter, but when the process terminated, no any other information:
# tailf /var/log/nginx-vts-exporter.log 
2017/09/11 14:58:39 Starting nginx_vts_exporter (version=0.6, branch=HEAD, revision=e48bd6899d8864b11b9f71f852b049ec3ad2ae26)
2017/09/11 14:58:39 Build context (go=go1.8.3, user=root@3b0fc1d0acb6, date=20170808-07:09:08)
2017/09/11 14:58:39 Starting Server at : :9913
2017/09/11 14:58:39 Metrics endpoint: /metrics
2017/09/11 14:58:39 Metrics namespace: nginx
2017/09/11 14:58:39 Scraping information from : http://localhost/status

I don't know why the process terminted automatically, please advise.

**Comment by hnlq715** [comment]
Maybe the process exits when your ssh terminal quits? Please try `nohup ./nginx-vts-exporter &` to launch this program

**Comment by smallfish01** [comment]
Yes, you are right, I used  "nohup" and the process is running ok now.
Thanks you very much!

**Comment by hnlq715** [comment]
Nice :-)

**Comment by dragonfly-net** [comment]
Scraping information from : http://localhost/status
How to replace it to more correct path like http://localhost/status/format/json ? I made
export NGINX_STATUS=http://localhost/status/format/json but unsuccessfully.

**Comment by turboevil** [comment]
> Scraping information from : http://localhost/status
> How to replace it to more correct path like http://localhost/status/format/json ? I made
> export NGINX_STATUS=http://localhost/status/format/json but unsuccessfully.

try http://localhost/status?json
