### ISSUE TITLE
Problems runing  exporter

### ISSUE THREAD

**Issue by ruben-herold** [hnlq715/nginx-vts-exporter#33]
hi,

I have  installed a vm  with a local prometheus install. I installed go and try to start the binary:

`./nginx-vts-exporter -nginx.scrape_uri=http://ngnx-01.example.org/format/json  -telemetry.endpoint=http://[::1]:9090/metrics`

I get the output:

`2017/09/13 20:19:44 Starting nginx_vts_exporter (version=0.6, branch=HEAD, revision=e48bd6899d8864b11b9f71f852b049ec3ad2ae26)
2017/09/13 20:19:44 Build context (go=go1.8.3, user=root@3b0fc1d0acb6, date=20170808-07:09:08)
2017/09/13 20:19:44 Starting Server at : :9913
2017/09/13 20:19:44 Metrics endpoint: http://[::1]:9090/metrics
2017/09/13 20:19:44 Metrics namespace: nginx
2017/09/13 20:19:44 Scraping information from : http://ngnx-01.example.org/format/json
`

an nothing happend. The ngn-01.example.org is reachable from the system, i have tested it with curl -I and a telnet ::1 9090 also works. 

In the tcpdump on the system I don't see any traffic leaving the box. No error messages nothing...

**Comment by ruben-herold** [comment]
@hnlq715 sorry forget to say that the platform is centos 7

**Comment by ruben-herold** [comment]
@hnlq715 same with build from current master. Seems todo nothing and don't send any error messages. Not even the timeout prints something out. Started now with:

`./nginx-vts-exporter -nginx.scrape_uri=http://ngnx-01.example.org/format/json -telemetry.endpoint=http://[::1]:9090/metrics -nginx.scrape_timeout=1`

**Comment by hnlq715** [comment]
You need to curl `localhost:9090/metrics` to get output data

**Comment by ruben-herold** [comment]
Why localhost? My setup ist:

ngnx-01.example.org <-- ngnix webserver with vts module enabled
ngnx-stats01.example.org <-- Server with prometheus and nginx-vts-exporter


ngnx-stats01.example.org  can reach http://ngnx-01.example.org/format/json and get the metrics via curl

ngnx-stats01.example.org  has the prometheus listen on [::1]:9090

I start the exporter with:

` ./nginx-vts-exporter -nginx.scrape_uri=http://ngnx-01.example.org/format/json -telemetry.endpoint=http://[::1]:9090/metrics -nginx.scrape_timeout=1` 

 and nothing happend

**Comment by hnlq715** [comment]
prometheus -> nginx-vtx-exporter -> nginx with vts

nginx-vts-exporter would pull metrics from nginx unless prometheus send pull request.

And I think you just misunderstood this concept.

**Comment by ruben-herold** [comment]
Ah ok sorry now I'm fine :-)

**Comment by ruben-herold** [comment]
Great works now, you should  write some more documentation even for people that are not familiar with go and prometheus

**Comment by hnlq715** [comment]
Sure, thanks for your advise.
