### ISSUE TITLE
Can't create binary

### ISSUE THREAD

**Issue by ruben-herold** [hnlq715/nginx-vts-exporter#34]
hi,

I'm no go expert but I followed your instructions and it does not build:

`[root@localhost ~]# mkdir go
[root@localhost ~]# cd go
[root@localhost go]# git clone https://github.com/hnlq715/nginx-vts-exporter.git
Klone nach 'nginx-vts-exporter'...
remote: Counting objects: 511, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 511 (delta 0), reused 2 (delta 0), pack-reused 507
Empfange Objekte: 100% (511/511), 18.18 MiB | 585.00 KiB/s, done.
Löse Unterschiede auf: 100% (237/237), done.
[root@localhost go]# cd nginx-vts-exporter/
[root@localhost nginx-vts-exporter]# make
>> formatting code
can't load package: package _/root/go/nginx-vts-exporter: cannot find package "_/root/go/nginx-vts-exporter" in any of:
	/usr/lib/golang/src/_/root/go/nginx-vts-exporter (from $GOROOT)
	/root/go/src/_/root/go/nginx-vts-exporter (from $GOPATH)
make: *** [format] Fehler 1
[root@localhost nginx-vts-exporter]# 
`

**Comment by hnlq715** [comment]
You should clone nginx-vts-exporter into `$(GOPATH)/src` :-)

**Comment by ruben-herold** [comment]
thx will try it at work today

**Comment by ruben-herold** [comment]
thx build runs find but still the samle like in #32
