### ISSUE TITLE
outBytes of type int

### ISSUE THREAD

**Issue by william-yang** [hnlq715/nginx-vts-exporter#42]
nginx_exporter 0.6 version

if nginx's outBytes  > 2 147 483 648 ; than nginx_exporter error

errorlog:
2017/11/02 20:20:08 json.Unmarshal failed json: cannot unmarshal number 2251611814 into Go struct field Server.outBytes of type int
2017/11/02 20:20:23 json.Unmarshal failed json: cannot unmarshal number 2251765921 into Go struct field Server.outBytes of type int

**Comment by hnlq715** [comment]
Thanks for reporting, and pull request is welcome :-)
