### ISSUE TITLE
Build docker image as `latest` and `vx.x` 

### ISSUE THREAD

**Issue by carlosjgp** [hnlq715/nginx-vts-exporter#50]
It would be great if we can access a more deterministic way to the latest version of this great exporter.

To access the latest changes the only way is using your docker image with the `latest` tag with the risk that we will pull the following release without knowing it and it might contain breaking changes.

This just happened to us https://github.com/hnlq715/nginx-vts-exporter/commit/03e03cfc4ddd179123558cec61174efa3b1be9b2

**Comment by carlosjgp** [comment]
I just realized that your Docker tags are in sync with your `releases`...

So maybe a note on your `README.md` file on the Docker section about it. :+1:

**Comment by hnlq715** [comment]
Maybe you could submit a PR for this :-) thanks a lot
