### ISSUE TITLE
Binaries for latest release

### ISSUE THREAD

**Issue by milipili** [hnlq715/nginx-vts-exporter#51]
Hi, it seems that the binaries are not available for the latest release (0.7.1 and 0.8).
Is that intentional?

**Comment by hnlq715** [comment]
Thanks for reporting, i will fix it ASAP

**Comment by towolf** [comment]
I made "sad emoji" as well, when I saw that no recent builds were available ...

**Comment by hnlq715** [comment]
fixed.
