### ISSUE TITLE
json.Unmarshal failed

### ISSUE THREAD

**Issue by xujpxm** [hnlq715/nginx-vts-exporter#54]
Scraping information, i got log error: " json.Unmarshal failed invalid character '<' looking for beginning of value"

**Comment by hnlq715** [comment]
Maybe you should looking for the contents returned from vts api.
Mostly this error occurred when the contents are not `json` string.

**Comment by xujpxm** [comment]
Fixed when I added the arg "-nginx.scrape_uri http://127.0.0.1/status/format/json ".
👍

**Comment by saclin** [comment]
I added the arg "-nginx.scrape_uri http://127.0.0.1/nginx-status/format/json ".
but get no json
Active connections: 2 
server accepts handled requests
 18 18 72 
Reading: 0 Writing: 1 Waiting: 1 

which is exactly same as I use "-nginx.scrape_uri http://127.0.0.1/nginx-status/"

why???  
thanks
