### ISSUE TITLE
exporter does not work for mulitple nginx instances

### ISSUE THREAD

**Issue by bsushant-athena** [hnlq715/nginx-vts-exporter#55]
Hi,

We have 2 nginx instances (with nginx-vts module installed) setup to serve the traffic.

We have setup one nginx-vts-exporter and configured it to scrape the metrics from "/status/format/json" endpoint.

Observation: metrics exposed from "/metrics" endpoint of nginx-vts-exporter doesn't include the information about the nginx instance from which the information was grabbed. Hence we are not able to plot the metrics against the nginx instance say in grafana/prometheus.

Does nginx-vts-exporter support to track metrics from multiple nginx instances? or Do we need to configure it differently to support multiple nginx instances setup?

VTS version: 0.1.14
nginx version: 1.12.0

for single instance of nginx we are getting proper data but for multiple it is causing issues.
Please help us asap!

**Comment by hnlq715** [comment]
`nginx-vts-exporter` does not support multiple instances right now. You need to run one exporter per nginx instance.

**Comment by bsushant-athena** [comment]
In my case I have two instances of nginx and on top of that we have load balancer which chooses the nginx instance in round robin fashion so I can not hard code(id:port) or point to particular nginx instance. Then how do I add two separate nginx vts exporters for two instances of nginx?

**Comment by hnlq715** [comment]
You should use exporter to connect nginx instance directly, instead of connect to the load balance.

**Comment by bsushant-athena** [comment]
ok so to resolve this issue we have added nginx its exporter inside our nginx and now we get the required correct data.

One other question I've is , this module does not provide any uptime data but when I hit /status I could see the metrics there ; it is just exporter is not exposing . @hnlq715  can you take this as an enhancement ?

**Comment by bsushant-athena** [comment]
@hnlq715 One other question I've is , this module does not provide any uptime data but when I hit /status I could see the metrics there ; it is just exporter is not exposing . @hnlq715 can you take this as an enhancement ?

**Comment by hnlq715** [comment]
yes, pull request is welcome：）

**Comment by bsushant-athena** [comment]
I'm not familiar with go language , could you please do that and release a new version ? That will be really helpful :)

**Comment by hnlq715** [comment]
No problem, I would take it into consideration. Thanks for your advise 😄

**Comment by hnlq715** [comment]
#29

**Comment by hnlq715** [comment]
Server info metrics added, and readme docs updated, please check the latest docker image.
