### ISSUE TITLE
nginx_upstream_response metric missing

### ISSUE THREAD

**Issue by 123BLiN** [hnlq715/nginx-vts-exporter#57]
Hello guys, 

Am I missing something? Where is the main metric - nginx_upstream_response?
As grafana dashboard has it preconfigured
https://github.com/hnlq715/nginx-vts-exporter/blob/3b84c4ecab8ccb98dc59e6a8a00d76ab7d7b852f/dashboard/nginx-vts-exporter.json#L635
I may assume it was present earlier but now it is missing in the latest version (0.9.1), if this is expected can you advice the version where it is still present?

**Comment by 123BLiN** [comment]
>  if this is expected can you advice the version where it is still present?
the version is 0.8
However there is one problem - for some reason instead of one metric that will have "backend" and "code" as tags we have two different metrics(
So it is not possible to answer on the simple question - which service backend is having problems

**Comment by bsushant-athena** [comment]
see latest released version 0.9.1 
https://github.com/hnlq715/nginx-vts-exporter/releases/tag/v0.9.1

**Comment by 123BLiN** [comment]
https://github.com/hnlq715/nginx-vts-exporter/blob/master/nginx_vts_exporter.go#L196
from what I see "backend" tag is missing on the metric

**Comment by hnlq715** [comment]
Could you please provide the detailed prometheus output here? Thanks.
And I guess, maybe the grafana dashboard json file is outdated.

**Comment by 123BLiN** [comment]
Hi! I'm sorry I propose to close this one, as the name of the topic is incorrect. 
I will create another one and possibly create pull request if I be able too.
In short we need "backend" tags across all upstream metrics, because we need to be able differentiate upstream errors per host and also to track load on upstream hosts separately.
