### ISSUE TITLE
Upstream requests per backend

### ISSUE THREAD

**Issue by hadret** [hnlq715/nginx-vts-exporter#59]
Hi,

currently the `nginx-vts-exporter` supports `Server requests` (1xx, 2xx etc.) and `Upstream requests` (1xx, 2xx etc.), but what would also be neat is feature already provided by vts plugin -- `Upstream requests per backend`. `Backends` are already working for `nginx_upstream_requestMsec` and `nginx_upstream_responseMsec` so, I'm assuming here, I think this should not be super difficult to implement.

Current state:
```
nginx_upstream_requests{code="1xx",instance="$INSTANCE",job="$JOB",upstream="$UPSTREAM"}
```

Feature request state:
```
nginx_upstream_requests{backend="$BACKEND",code="1xx",instance="$INSTANCE",job="$JOB",upstream="$UPSTREAM"}
```

Please let me know whether there's anything not clear about the issue.

All the best
Filip

**Comment by yastij** [comment]
ref kubernetes/ingress-nginx#2116

**Comment by hnlq715** [comment]
Sounds great, and pull request is welcome :-)
