### ISSUE TITLE
why I got so little metrics

### ISSUE THREAD

**Issue by 13567436138** [hnlq715/nginx-vts-exporter#64]
[root@node1 export]# curl http://10.96.174.195:9913/metrics
# HELP nginx_vts_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which nginx_vts_exporter was built.
# TYPE nginx_vts_exporter_build_info gauge
nginx_vts_exporter_build_info{branch="HEAD",goversion="go1.9.4",revision="43b45563691a369b8fa12f7383d185a6b28d18ea",version="0.10.3"} 1

**Comment by hnlq715** [comment]
Please make sure your nginx is compiled with [vts](https://github.com/vozlt/nginx-module-vts) correctly.

**Comment by jackzing** [comment]
+1
Any solutions?

**Comment by uniti-in-diversity** [comment]
+1 Any solution?
I have nginx 1.12 with module nginx-module-vts
http://domain.name/status/format/json
or
http://domain.name/status/format/prometheus
shows all metrics, but nginx-vts-exporter doesn`t
I tried different version (0.10.0, 0.10.3, 0.10.7)
