### ISSUE TITLE
json type error??

### ISSUE THREAD

**Issue by saclin** [hnlq715/nginx-vts-exporter#67]
I added the arg "-nginx.scrape_uri http://127.0.0.1/nginx-status/format/json ".
but get no json:"""
Active connections: 2
server accepts handled requests
18 18 72
Reading: 0 Writing: 1 Waiting: 1
"""
which is exactly same as I use "-nginx.scrape_uri http://127.0.0.1/nginx-status/"
so the exporter log "2018/08/08 11:00:46 json.Unmarshal failed invalid character 'A' looking for beginning of value
"
why???
thanks

**Comment by hnlq715** [comment]
This exporter supports nginx-vts-module only, not the status module.

**Comment by saclin** [comment]
thanks. I confused with another exporter
