### ISSUE TITLE
json.Unmarshal failed

### ISSUE THREAD

**Issue by Lvzhenqian** [hnlq715/nginx-vts-exporter#75]
[root@localhost nginx_export]# ./nginx-vts-exporter -nginx.scrape_uri=http://xxx/status/format/json
2019/05/20 18:57:51 Starting nginx_vts_exporter (version=0.10.3, branch=HEAD, revision=8aa2881c7050d9b28f2312d7ce99d93458611d04)
2019/05/20 18:57:51 Build context (go=go1.10, user=root@56ca8763ee48, date=20180328-05:47:47)
2019/05/20 18:57:51 Starting Server at : :9913
2019/05/20 18:57:51 Metrics endpoint: /metrics
2019/05/20 18:57:51 Metrics namespace: nginx
2019/05/20 18:57:51 Scraping information from : http://xxx/status/format/json
2019/05/20 18:58:28 json.Unmarshal failed invalid character '\x1f' in string literal

```go
func (e *Exporter) Collect(ch chan<- prometheus.Metric) {
	body, err := fetchHTTP(e.URI, time.Duration(*nginxScrapeTimeout)*time.Second)()
	if err != nil {
		log.Println("fetchHTTP failed", err)
		return
	}
	defer body.Close()

	data, err := ioutil.ReadAll(body)
	if err != nil {
		log.Println("ioutil.ReadAll failed", err)
		return
	}
      // add this  code to remove character . now it worker 
	for index, char := range data {
		switch {
		case char > '~':
			data[index] = ' '
		case char == '\r':
		case char == '\n':
		case char == '\t':
		case char < ' ':
			data[index] = ' '
		}
	}
	var nginxVtx NginxVts
	err = json.Unmarshal(data, &nginxVtx)
```

**Comment by hnlq715** [comment]
可以看下你的http://xxx/status/format/json 这个页面是什么数据

Please check what is it in your http://xxx/status/format/json page

**Comment by Lvzhenqian** [comment]
[json.txt](https://github.com/hnlq715/nginx-vts-exporter/files/3201054/json.txt)
这是我的json文件，在serverZones里面拿到有特殊字符，所以解析失败了。

**Comment by hnlq715** [comment]
@Lvzhenqian 
Maybe you should justify your nginx config instead of replaceing special charactors...
也许你应该调整nginx配置，而不是替换特殊字符。。。

**Comment by Lvzhenqian** [comment]
> @Lvzhenqian
> Maybe you should justify your nginx config instead of replaceing special charactors...
> 也许你应该调整nginx配置，而不是替换特殊字符。。。

serverZones 里的server_name，nginx-vts-module 拿出来时就有特殊字符。没看到有相关的详细配置。
vhost_traffic_status_filter_by_host on; 配置都加上了。所以我也是没办法中的办法 :)
