### ISSUE TITLE
 was collected before with the same name and label values

### ISSUE THREAD

**Issue by lizeyun** [hnlq715/nginx-vts-exporter#78]
collected metric nginx_upstream_bytes label:<name:"backend" value:"xx:8380" > label:<name:"direction" value:"out" > label:<name:"upstream" value:"xx_web" > counter:<value:0 >  was collected before with the same name and label values

What can i do

**Comment by lizeyun** [comment]
i have find how cause the problem , 
in case some upstream_addr has not virt host to use

remove the upstream solve this

**Comment by xudingjun3131** [comment]
upstream can not use localhost or domain,it must to be used ip address
