### ISSUE TITLE
Automated Docker Hub Build

### ISSUE THREAD

**Issue by galexrt** [hnlq715/nginx-vts-exporter#8]
Is there an automated Docker Hub build available? If not would it be possible to set one up.
I only saw this one https://hub.docker.com/r/albertdixon/nginx-vts-exporter/. But this doesn't seem to be an automated built image.
It would be awesome to have an automated build of this image.

***

One way would be to use a golang image and built it in it.

**Comment by hnlq715** [comment]
Thanks for the advise, I would consider it 😄

**Comment by hnlq715** [comment]
@galexrt 
I have already set up an automated Docker Hub build, have fun :-)
https://hub.docker.com/r/sophos/nginx-vts-exporter/

**Comment by galexrt** [comment]
@hnlq715 Thank you! :+1: 
I'm going to submit an PR to update the `README.md` to point to the Docker Hub build.

**Comment by galexrt** [comment]
One thing I just noticed is that the tags of the repo aren't built. Could you please also add a wildcard regex for building tags to the Docker Hub build settings?

**Comment by hnlq715** [comment]
Sure, but old versions of nginx-vts-exporter are quite different with v0.3 in many ways.

**Comment by galexrt** [comment]
Could you manually add the `v0.3` as a tag on Docker Hub build settings and trigger a build that the image tag becomes available to use (currently only `latest`/master tag has been built).
