### ISSUE TITLE
Export Go Process Metrics

### ISSUE THREAD

**Issue by pritpal-sabharwal** [hnlq715/nginx-vts-exporter#84]
I noticed that Go process metrics are intentionally not being exported:

https://github.com/hnlq715/nginx-vts-exporter/blob/60540c64a6a13341923e93bb65bbfad11b78939e/nginx_vts_exporter.go#L377-L378

I think it would make sense making this a configurable option. If there is no objection, I'm happy submitting a PR with the changes.

**Comment by pritpal-sabharwal** [comment]
See https://github.com/hnlq715/nginx-vts-exporter/pull/85

**Comment by hnlq715** [comment]
@pritpal-sabharwal Thanks for you contribution!
