### ISSUE TITLE
ENV var issues

### ISSUE THREAD

**Issue by MrMMorris** [hnlq715/nginx-vts-exporter#9]
Me again. 

I noticed some issues/quirks with the env vars and I would normally submit a PR, but I'm not sure how to handle things in terms of backwards compatibility etc.

1. Is the NGIX_HOST env var supposed to be named NGINX_HOST? not a big issue, but might be confusing for some.

2. In the README, the example docker run command provides `--env NGIX_HOST="http://localhost/status/format/json"` (with appended status path), but in the `docker-entrypoint.sh` it has `default_status="$NGIX_HOST/status/format/json"` (which, again, appends the status path). I think it should either have `--env NGINX_STATUS="http://localhost/status/format/json"` or `--env NGIX_HOST="http://localhost"`

**Comment by hnlq715** [comment]
@MrMMorris Thanks.
We have not released stable version at this moment, so we could consider simple and correctness over backwards compatibility, and PR would be welcome :-)

**Comment by hnlq715** [comment]
fixed :-)
