### ISSUE TITLE
Does it support multiple pod in k8s?

### ISSUE THREAD

**Issue by Taymindis** [hnlq715/nginx-vts-exporter#96]
for example, nginx_vts_xxxxx{instance="$instance"} ??

**Comment by hnlq715** [comment]
This should be configured in promethues

**Comment by Taymindis** [comment]
But it only show me single instance in Prometheus metrics if I replica more than 1 pods

**Comment by Taymindis** [comment]
I managed to get it done via using /promethues from vts-module

Thanks
