### ISSUE TITLE
how to build in arm/aarch64  env ?

### ISSUE THREAD

**Issue by szboyb** [hnlq715/nginx-vts-exporter#97]

**Comment by tgb7895** [comment]
+1

**Comment by hnlq715** [comment]
Maybe you should try this?

```bash
GOOS=linux GOARCH=arm64 go build
```

**Comment by Zzqqc** [comment]
+2

**Comment by wwh131** [comment]
+3

**Comment by wwh131** [comment]
![image](https://github.com/hnlq715/nginx-vts-exporter/assets/134466725/81d90009-fc54-4a13-8979-5b42bcb52fa8)
在ARM64上make报错了

**Comment by hnlq715** [comment]
https://github.com/hnlq715/nginx-vts-exporter/releases/tag/v0.10.8

here is the release with arm64 binary assets

**Comment by wwh131** [comment]
That's right, brother. I'll try and see if it works right away!
