### ISSUE TITLE
Release v0.10.7 has no assets

### ISSUE THREAD

**Issue by HansGerry** [hnlq715/nginx-vts-exporter#99]
Hi,
can you take a look at the latest release? It only contains the sourcecode, the binary assets are missing

**Comment by wwh131** [comment]
对啊，怎么没有ARM版的呢

**Comment by hnlq715** [comment]
I've refact this release process and here is the release v0.10.8 with binary assets.

**Comment by hnlq715** [comment]
https://github.com/hnlq715/nginx-vts-exporter/releases/tag/v0.10.8
